core:
  security:
    authorize:
      permitUrls:
        - /hello
        - /hello2
      unAuthorizePage: /login.html
    authentication:
      loginType: REDIRECT
      loginErrorPage: http://www.baidu.com
      loginSuccessPage: http://www.google.com